[theme]
primaryColor = "#10B981"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#1F2937"
textColor = "#FAFAFA"
font = "sans serif"
base = "dark"

[server]
headless = true
port = 8501

[browser]
gatherUsageStats = false

[server]
maxUploadSize = 5
enableXsrfProtection = true
enableCORS = false
